token = "<TOKEN>"
ops = "ops.txt"
cmdlist = "list.txt"
opcmdlist = "oplist.txt"
log = "log.txt"
promos = "promos.txt"
expired = "expired.txt"
cache = "cache"
info = "Sourcery\nBot for sharing precious information.\nMade by Ingenious, 2018."
noperms = "You don't have enough permissions to execute this command"
invalargs = "Invalid arguments!"
alreadymod = "User has already been promoted!"
notmod = "User wasn't promoted"
activated = "Promocode was activated!"
isexpired = "Promocode is expired!"
listA = "/activate <PROMOCODE> - activates promocode\n/help - shows this list\n/info - shows info about this bot"
listB = "/admins - shows admins ids\n/getpromos - shows available promocodes\n/promote <ID> - promotes user to admin\n"\
        + "/downgrade <ID> - removes user from admins\n/generate <PROMO LINK> <AMOUNT> - generates AMOUNT promocodes\n"\
        + "/getexp - shows expired promocodes"
notfound = "Couldn't find promocode!"
